version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - crud-network

  php:
    build: .
    volumes:
      - ./app:/var/www/html
    networks:
      - crud-network

  mysql:
    image: mysql:8.0
    ports:
      - "90:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_app
      MYSQL_USER: cruduser
      MYSQL_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - crud-network

networks:
  crud-network:

volumes:
  mysql_data:
